### ISSUE TITLE
Side Effects in the Array functions

### ISSUE THREAD

**Issue by raguay** [kingsleyh/array-extra#1] opened 2018-09-07 07:44 UTC
Hi,

The concat and append functions has the side effect of changing the last array for concat and the first array in append to the combined array. I'm using it to combine two arrays that are in a store to generate a unordered list. Everytime the list is re-evaluated, the list doubles in size due to the concat changing the store's array.

Was the intended effect? If so, do you have one that is more pure functional?

Thanks.

**Comment by kingsleyh** [comment] 2018-09-07 08:13
Hi - ah ok this is not what was intended - I will fix it and make another release shortly - thanks for pointing this out :)

**Comment by kingsleyh** [comment] 2018-09-07 08:18
could you paste me a small example of some code that exhibits this behaviour - just so I fully understand

**Comment by raguay** [comment] 2018-09-07 08:33
I'm using it here:

   get mainScriptList : Array(ScriptRecord) {
      Array.select((item : ScriptRecord) : Bool => {
         if(searchName == "") {
            true
         } else {
            Utility.stringIncludes(String.toLowerCase(item.name),
String.toLowerCase(searchName))
         }
      }, Array.Extra.concat([userScripts,predefinedScripts]))
   }

userScripts and predefinedScripts are arrays of ScriptRecord records. This
get is called to display an unordered list. When the list is shown, it
re-evaluates the function and the userScripts get the predefinedScripts
added to it again (or, at least that is how it seems.). The scripts
originally in the userScripts is only in the list once. If I swap the
order, then the other array is added in multiple times. The
Utility.stringIncludes function is just a wrap for the JavaScript
String.includes. The searchName is the contents of the input field to limit
the number of items by only showing the items that contains the searchName
characters.

**Comment by kingsleyh** [comment] 2018-09-07 08:35
ok great thanks - I see the issue - I'll have it fixed in a sec - I totally forgot about mutability and focused on performance.

**Comment by kingsleyh** [comment] 2018-09-07 08:40
fixed in latest tag - 0.0.3

**Closed as completed by kingsleyh** 2018-09-07 08:40 UTC

**Comment by raguay** [comment] 2018-09-07 08:52
Alright. That fixed it. I've been going over everything trying to make sure
I didn't have a funny side-effect somewhere. It is nice to have pure
functions. Life is much easier! Thanks for fixing it.
